유챗 위키,전보,송금 및 위키링크 기능
gubug0/aun-helper pull request #25
Opened 2022-06-10 07:21 UTC by LIMECAKE

유챗 위키,전보,송금 및 위키링크 기능 추가

2022-06-11 12:11 UTC, gubug0 requested changes

2022-06-11 12:11 UTC, gubug0 commented on chatExtender.js
> +    let EXTENSION_ID = "ppnelmgdamnbgcjfgplioaiejcpcfeol";
extensionId 는 제가 이해하는 바로는 고정된 값이 아닙니다.

2022-06-13 10:37 UTC, LIMECAKE commented on chatExtender.js
> +    let EXTENSION_ID = "ppnelmgdamnbgcjfgplioaiejcpcfeol";
앗 네, 그래서 chatHelper.js 에서 chatExtender.js를 inject할때 script tag에 현재 extension 의 id를 같이 넘겨서 받을 수 있도록 작업해놨습니다. 기본값이 사용될 일이 없지만 혹시나 몰라 초기화하는 겸 구벅님 정식버전 id로 세팅해놨습니다!

2022-06-13 10:37 UTC, LIMECAKE commented
#27 에 포함되었습니다!

2022-06-13 10:38 UTC, closed without merging